#include "common/platform_ops.h"
#include "common/errors.h"
#include "platform/linux/utils.h"
#include "platform/linux/window.h"
#include "platform/linux/menu.h"
#include "platform/linux/elements.h"

static int box_add_wrapper(NGHandle b, NGHandle e, float w) {
    (void)w;
    return ng_linux_box_add(b, e);
}

static const ng_platform_ops_t linux_ops = {
    .init = ng_linux_init,
    .cleanup = ng_linux_cleanup,
    .run = ng_linux_run,
    .poll_events = ng_linux_poll_events,
    .create_window = ng_linux_create_window,
    .create_window_with_type = ng_linux_create_window_with_type,
    .destroy_window = ng_linux_destroy_window,
    .window_set_title = ng_linux_window_set_title,
    .window_set_size = ng_linux_window_set_size,
    .window_get_size = ng_linux_window_get_size,
    .window_request_close = ng_linux_window_request_close,
    .window_is_focused = ng_linux_window_is_focused,
    .window_set_cursor_visible = ng_linux_window_set_cursor_visible,
    .window_set_cursor_grab = ng_linux_window_set_cursor_grab,
    .window_get_content_view = NULL,
    .window_show = ng_linux_window_show,
    .window_hide = ng_linux_window_hide,
    .window_is_visible = ng_linux_window_is_visible,
    .window_set_position = ng_linux_window_set_position,
    .window_get_position = ng_linux_window_get_position,
    .window_get_xcb_handle = ng_linux_window_get_xcb_handle,
    .window_get_wayland_handle = ng_linux_window_get_wayland_handle,
    .create_menu = ng_linux_create_menu,
    .destroy_menu = ng_linux_destroy_menu,
    .attach_menu = ng_linux_attach_menu,
    .add_menu_item = ng_linux_add_menu_item,
    .add_menu_separator = ng_linux_add_menu_separator,
    .create_submenu = ng_linux_create_submenu,
    .create_button = ng_linux_create_button,
    .button_invalidate = ng_linux_button_invalidate,
    .create_label = ng_linux_create_label,
    .label_invalidate = ng_linux_label_invalidate,
    .create_box = ng_linux_create_box,
    .box_invalidate = ng_linux_box_invalidate,
    .box_add = box_add_wrapper,
    .set_window_content = ng_linux_set_window_content,
    .create_split_view = ng_linux_create_split_view,
    .split_view_add = ng_linux_split_view_add,
    .split_view_set_divider_position = ng_linux_split_view_set_divider_position,
    .create_text_editor = ng_linux_create_text_editor,
    .text_editor_invalidate = ng_linux_text_editor_invalidate,
    .create_text_view = ng_linux_create_text_view,
    .text_view_invalidate = ng_linux_text_view_invalidate,
    .create_text_field = NULL,
    .set_text_content = ng_linux_set_text_content,
    .get_text_content = ng_linux_get_text_content,
    .free_text_content = ng_linux_free_text_content,
    .create_canvas = ng_linux_create_canvas,
    .canvas_invalidate = ng_linux_canvas_invalidate,
    .canvas_invalidate_rect = ng_linux_canvas_invalidate_rect,
    .canvas_update_buffer = ng_linux_canvas_update_buffer,
    .canvas_get_size = ng_linux_canvas_get_size,
    .canvas_get_window = ng_linux_canvas_get_window,
    .canvas_get_native_handle = ng_linux_canvas_get_native_handle,
    .canvas_get_xcb_handle = ng_linux_canvas_get_xcb_handle,
    .canvas_get_wayland_handle = ng_linux_canvas_get_wayland_handle,
    .get_scale_factor = ng_linux_get_scale_factor,
    .window_set_scale_factor_callback = ng_linux_window_set_scale_factor_callback,
    .window_set_lifecycle_callback = ng_linux_window_set_lifecycle_callback,
    .create_image_view = ng_linux_create_image_view,
    .image_view_load_from_path = ng_linux_image_view_load_from_path,
    .image_view_load_from_data = ng_linux_image_view_load_from_data,
    .image_view_set_scaling = ng_linux_image_view_set_scaling,
    .image_view_invalidate = ng_linux_image_view_invalidate,
    .create_slider = ng_linux_create_slider,
    .slider_set_value = ng_linux_slider_set_value,
    .slider_get_value = ng_linux_slider_get_value,
    .slider_set_enabled = ng_linux_slider_set_enabled,
    .slider_invalidate = ng_linux_slider_invalidate,
    .create_checkbox = ng_linux_create_checkbox,
    .checkbox_set_checked = ng_linux_checkbox_set_checked,
    .checkbox_get_checked = ng_linux_checkbox_get_checked,
    .checkbox_set_enabled = ng_linux_checkbox_set_enabled,
    .checkbox_invalidate = ng_linux_checkbox_invalidate,
    .create_progress_bar = ng_linux_create_progress_bar,
    .progress_bar_set_value = ng_linux_progress_bar_set_value,
    .progress_bar_set_indeterminate = ng_linux_progress_bar_set_indeterminate,
    .progress_bar_set_enabled = ng_linux_progress_bar_set_enabled,
    .progress_bar_invalidate = ng_linux_progress_bar_invalidate,
    .create_combo_box = ng_linux_create_combo_box,
    .combo_box_add_item = ng_linux_combo_box_add_item,
    .combo_box_set_selected = ng_linux_combo_box_set_selected,
    .combo_box_get_selected = ng_linux_combo_box_get_selected,
    .combo_box_clear = ng_linux_combo_box_clear,
    .combo_box_set_enabled = ng_linux_combo_box_set_enabled,
    .combo_box_invalidate = ng_linux_combo_box_invalidate,
    .create_tab_bar = ng_linux_create_tab_bar,
    .tab_bar_add_tab = ng_linux_tab_bar_add_tab,
    .tab_bar_remove_tab = ng_linux_tab_bar_remove_tab,
    .tab_bar_set_selected = ng_linux_tab_bar_set_selected,
    .tab_bar_get_selected = ng_linux_tab_bar_get_selected,
    .tab_bar_invalidate = ng_linux_tab_bar_invalidate,
    .create_sidebar_list = ng_linux_create_sidebar_list,
    .sidebar_list_add_section = ng_linux_sidebar_list_add_section,
    .sidebar_list_add_item = ng_linux_sidebar_list_add_item,
    .sidebar_list_set_selected = ng_linux_sidebar_list_set_selected,
    .sidebar_list_get_selected = ng_linux_sidebar_list_get_selected,
    .sidebar_list_clear = ng_linux_sidebar_list_clear,
    .sidebar_list_invalidate = ng_linux_sidebar_list_invalidate,
};

void linux_register_ops(void) {
    ng_platform_register_ops(&linux_ops);
}
