[package]
name = "aurea-runtime"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Window event loop lifecycle and scheduling for Aurea"
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
aurea-foundation = { path = "../aurea-foundation", version = "0.1.0" }
log = "0.4.29"
