#include "common/platform_ops.h"
#include "common/errors.h"
#include "platform/windows/utils.h"
#include "platform/windows/window.h"
#include "platform/windows/menu.h"
#include "platform/windows/elements.h"

static int box_add_wrapper(NGHandle b, NGHandle e, float w) {
    (void)w;
    return ng_windows_box_add(b, e);
}

static const ng_platform_ops_t windows_ops = {
    .init = ng_windows_init,
    .cleanup = ng_windows_cleanup,
    .run = ng_windows_run,
    .poll_events = ng_windows_poll_events,
    .create_window = ng_windows_create_window,
    .create_window_with_type = ng_windows_create_window_with_type,
    .destroy_window = ng_windows_destroy_window,
    .window_set_title = ng_windows_window_set_title,
    .window_set_size = ng_windows_window_set_size,
    .window_get_size = ng_windows_window_get_size,
    .window_request_close = ng_windows_window_request_close,
    .window_is_focused = ng_windows_window_is_focused,
    .window_set_cursor_visible = ng_windows_window_set_cursor_visible,
    .window_set_cursor_grab = ng_windows_window_set_cursor_grab,
    .window_get_content_view = NULL,
    .window_show = ng_windows_window_show,
    .window_hide = ng_windows_window_hide,
    .window_is_visible = ng_windows_window_is_visible,
    .window_set_position = ng_windows_window_set_position,
    .window_get_position = ng_windows_window_get_position,
    .window_get_xcb_handle = NULL,
    .window_get_wayland_handle = NULL,
    .create_menu = ng_windows_create_menu,
    .destroy_menu = ng_windows_destroy_menu,
    .attach_menu = ng_windows_attach_menu,
    .add_menu_item = ng_windows_add_menu_item,
    .add_menu_separator = ng_windows_add_menu_separator,
    .create_submenu = ng_windows_create_submenu,
    .create_button = ng_windows_create_button,
    .button_invalidate = ng_windows_button_invalidate,
    .create_label = ng_windows_create_label,
    .label_invalidate = ng_windows_label_invalidate,
    .create_box = ng_windows_create_box,
    .box_invalidate = ng_windows_box_invalidate,
    .box_add = box_add_wrapper,
    .set_window_content = ng_windows_set_window_content,
    .create_split_view = ng_windows_create_split_view,
    .split_view_add = ng_windows_split_view_add,
    .split_view_set_divider_position = ng_windows_split_view_set_divider_position,
    .create_text_editor = ng_windows_create_text_editor,
    .text_editor_invalidate = ng_windows_text_editor_invalidate,
    .create_text_view = ng_windows_create_text_view,
    .text_view_invalidate = ng_windows_text_view_invalidate,
    .create_text_field = ng_windows_create_text_field,
    .set_text_content = ng_windows_set_text_content,
    .get_text_content = ng_windows_get_text_content,
    .free_text_content = ng_windows_free_text_content,
    .create_canvas = ng_windows_create_canvas,
    .canvas_invalidate = ng_windows_canvas_invalidate,
    .canvas_invalidate_rect = ng_windows_canvas_invalidate_rect,
    .canvas_update_buffer = ng_windows_canvas_update_buffer,
    .canvas_get_size = ng_windows_canvas_get_size,
    .canvas_get_window = ng_windows_canvas_get_window,
    .canvas_get_native_handle = ng_windows_canvas_get_native_handle,
    .canvas_get_xcb_handle = NULL,
    .canvas_get_wayland_handle = NULL,
    .get_scale_factor = ng_windows_get_scale_factor,
    .window_set_scale_factor_callback = ng_windows_window_set_scale_factor_callback,
    .window_set_lifecycle_callback = ng_windows_window_set_lifecycle_callback,
    .create_image_view = ng_windows_create_image_view,
    .image_view_load_from_path = ng_windows_image_view_load_from_path,
    .image_view_load_from_data = ng_windows_image_view_load_from_data,
    .image_view_set_scaling = ng_windows_image_view_set_scaling,
    .image_view_invalidate = ng_windows_image_view_invalidate,
    .create_slider = ng_windows_create_slider,
    .slider_set_value = ng_windows_slider_set_value,
    .slider_get_value = ng_windows_slider_get_value,
    .slider_set_enabled = ng_windows_slider_set_enabled,
    .slider_invalidate = ng_windows_slider_invalidate,
    .create_checkbox = ng_windows_create_checkbox,
    .checkbox_set_checked = ng_windows_checkbox_set_checked,
    .checkbox_get_checked = ng_windows_checkbox_get_checked,
    .checkbox_set_enabled = ng_windows_checkbox_set_enabled,
    .checkbox_invalidate = ng_windows_checkbox_invalidate,
    .create_progress_bar = ng_windows_create_progress_bar,
    .progress_bar_set_value = ng_windows_progress_bar_set_value,
    .progress_bar_set_indeterminate = ng_windows_progress_bar_set_indeterminate,
    .progress_bar_set_enabled = ng_windows_progress_bar_set_enabled,
    .progress_bar_invalidate = ng_windows_progress_bar_invalidate,
    .create_combo_box = ng_windows_create_combo_box,
    .combo_box_add_item = ng_windows_combo_box_add_item,
    .combo_box_set_selected = ng_windows_combo_box_set_selected,
    .combo_box_get_selected = ng_windows_combo_box_get_selected,
    .combo_box_clear = ng_windows_combo_box_clear,
    .combo_box_set_enabled = ng_windows_combo_box_set_enabled,
    .combo_box_invalidate = ng_windows_combo_box_invalidate,
    .create_tab_bar = ng_windows_create_tab_bar,
    .tab_bar_add_tab = ng_windows_tab_bar_add_tab,
    .tab_bar_remove_tab = ng_windows_tab_bar_remove_tab,
    .tab_bar_set_selected = ng_windows_tab_bar_set_selected,
    .tab_bar_get_selected = ng_windows_tab_bar_get_selected,
    .tab_bar_invalidate = ng_windows_tab_bar_invalidate,
    .create_sidebar_list = ng_windows_create_sidebar_list,
    .sidebar_list_add_section = ng_windows_sidebar_list_add_section,
    .sidebar_list_add_item = ng_windows_sidebar_list_add_item,
    .sidebar_list_set_selected = ng_windows_sidebar_list_set_selected,
    .sidebar_list_get_selected = ng_windows_sidebar_list_get_selected,
    .sidebar_list_clear = ng_windows_sidebar_list_clear,
    .sidebar_list_invalidate = ng_windows_sidebar_list_invalidate,
};

void windows_register_ops(void) {
    ng_platform_register_ops(&windows_ops);
}
